# Generated by Django 3.2.5 on 2021-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_bitrate',
            field=models.FloatField(default=128),
        ),
        migrations.AddField(
            model_name='video',
            name='video_bitrate',
            field=models.FloatField(default=768),
        ),
    ]
