# Generated by Django 3.2.5 on 2021-08-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210820_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='videos.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='videos.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(),
        ),
    ]
