# Generated by Django 3.2.5 on 2021-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210824_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='video',
            name='artists',
            field=models.ManyToManyField(blank=True, to='videos.Artist'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
