# Generated by Django 3.2.5 on 2021-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210824_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='videos',
            field=models.ManyToManyField(blank=True, to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='full_path',
            field=models.FilePathField(unique=True),
        ),
    ]
